name:                dd-cc-hask
version:             0.1.0.0
github:              "githubuser/dd-cc-hask"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dd-cc-hask#readme>

dependencies:
- base >= 4.7 && < 5
- constrained-categories
- tagged
- warp
- wai
- http-types
- blaze-builder
- text
- recursion-schemes
- free
- blaze-markup
- bifunctors
- transformers
- deepseq
- vector
- nice-html

build-depends:
- tagged

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  dd-cc-hask-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dd-cc-hask

tests:
  dd-cc-hask-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dd-cc-hask
